"""
B.I.M.A Core — Cloud Backup (Auto Git Sync)
Otomatis commit output + memory + vault ke private GitHub repo setiap dijalankan.

Setup awal (sekali saja):
  cd /home/bima_lucian/BIMA_CORE
  git init
  git remote add origin https://github.com/USERNAME/bima-core-backup.git
  git branch -M main

Jalankan manual:  python tools/cloud_backup.py
Jadwal otomatis:  crontab -e → 0 2 * * * cd /home/bima_lucian/BIMA_CORE && python3 tools/cloud_backup.py
"""
import subprocess
import os
from datetime import datetime
from pathlib import Path

BASE_DIR = Path(__file__).parent.parent

# Folder yang di-backup
BACKUP_DIRS = [
    "outputs",
    "memory",
    "Bima_Vault",
    "vault_index",
    "logs",
    "frontend/personality.json",
]

# File yang di-exclude dari backup (sensitif)
GITIGNORE_CONTENT = """# Auto-generated by cloud_backup.py
.env
bima_env/
__pycache__/
*.pyc
node_modules/
logs/error.log
outputs/pet_event.json
"""

def run_git(cmd, cwd=None):
    """Jalankan git command dan return output"""
    result = subprocess.run(
        f"git {cmd}",
        shell=True,
        cwd=cwd or str(BASE_DIR),
        capture_output=True,
        text=True
    )
    return result.returncode, result.stdout.strip(), result.stderr.strip()

def backup():
    print("☁️  B.I.M.A Core — Cloud Backup")
    print(f"   Direktori: {BASE_DIR}")
    print(f"   Waktu: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
    
    # Cek apakah git sudah di-init
    code, out, err = run_git("status")
    if code != 0:
        print("❌ Git belum di-init! Jalankan ini dulu:")
        print("   cd /home/bima_lucian/BIMA_CORE")
        print("   git init")
        print("   git remote add origin https://github.com/USERNAME/bima-core-backup.git")
        return False
    
    # Pastikan .gitignore ada
    gitignore_path = BASE_DIR / ".gitignore"
    if not gitignore_path.exists():
        gitignore_path.write_text(GITIGNORE_CONTENT)
        print("  📝 .gitignore dibuat")
    
    # Add semua file yang relevan
    for d in BACKUP_DIRS:
        target = BASE_DIR / d
        if target.exists():
            run_git(f"add {d}")
            print(f"  📂 Added: {d}")
    
    # Juga add file utama
    for f in ["main.py", "config.py", "ecosystem.config.js", "requirements.txt", ".gitignore"]:
        if (BASE_DIR / f).exists():
            run_git(f"add {f}")
    
    # Add semua teams dan tools
    run_git("add teams/")
    run_git("add tools/")
    run_git("add frontend/")
    
    # Cek apakah ada perubahan
    code, status, _ = run_git("diff --cached --stat")
    if not status:
        print("\n  ✅ Tidak ada perubahan baru. Backup sudah up-to-date!")
        return True
    
    # Commit
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    commit_msg = f"🤖 Auto-backup: {timestamp}"
    code, out, err = run_git(f'commit -m "{commit_msg}"')
    if code == 0:
        print(f"\n  ✅ Commit: {commit_msg}")
    else:
        print(f"\n  ⚠️ Commit warning: {err}")
    
    # Push (opsional — hanya jika remote sudah di-setup)
    code, out, err = run_git("remote -v")
    if "origin" in out:
        print("  ☁️ Pushing ke remote...")
        code, out, err = run_git("push origin main")
        if code == 0:
            print("  ✅ Push berhasil!")
        else:
            print(f"  ⚠️ Push gagal (mungkin belum setup remote): {err}")
    else:
        print("  ℹ️ Remote belum di-setup, commit hanya lokal.")
    
    return True

if __name__ == "__main__":
    backup()
